Biblioteka/Models/Loan.cs
namespace Biblioteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Loan")]
    public partial class Loan
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Id { get; set; }

        public int UserId { get; set; }

        public int BookId { get; set; }

        public DateTime StartOfLoan { get; set; }

        public DateTime? EndOfLoan { get; set; }
    }
}

Biblioteka/Controllers/LoansController.cs
using Biblioteka.DTO;
using Biblioteka.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Biblioteka.Controllers
{
    public class LoansController : Controller
    {
        private DbLibrary _db = new DbLibrary();
        // GET: Loans
        public ActionResult Index()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            var l = _db.Loan.ToList();
            var listofloans = new List<LoanDTO>();
            foreach(var a in l)
            {
                var loan = new LoanDTO();
                var name = _db.Book.Where(x => x.Id.Equals(a.BookId)).FirstOrDefault();
                loan.Id = a.Id;
                loan.BookName = name.Name;
                loan.StartOfLoan = a.StartOfLoan;
                loan.EndOfLoan = a.EndOfLoan;
                if (a.UserId == int.Parse(Session["idUser"].ToString()))
                {
                    if(a.EndOfLoan == null)
                    {
                        loan.Status = "Active";
                    }
                    else
                    {
                        loan.Status = "Ended";
                    }
                    listofloans.Add(loan);
                }
            }
            return View(listofloans);
        }
        public ActionResult Loan(int id)
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            var loan = new Loan();
            loan.BookId = id;
            loan.UserId = int.Parse(Session["idUser"].ToString());
            loan.StartOfLoan = DateTime.Now;
            loan.EndOfLoan = null;
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                int i = Guid.NewGuid().GetHashCode();

                loan.Id = BitConverter.ToInt32(Guid.NewGuid().ToByteArray(), 0);
                _db.Configuration.ValidateOnSaveEnabled = false;
                var book = _db.Book.FirstOrDefault(x => x.Id.Equals(id));
                book.Quantity -= 1;
                if(book.Quantity < 0)
                {
                    return RedirectToAction("Index", "Books", "");
                }
                var userid = int.Parse(Session["idUser"].ToString());
                if (_db.Loan.Where(x => x.UserId.Equals(userid) && x.EndOfLoan.Equals(null)).Count() < 5)
                {
                    if (_db.Loan.Where(x => x.UserId.Equals(userid) && x.BookId.Equals(book.Id) && x.EndOfLoan.Equals(null)).Count() == 0)
                    {
                        _db.Loan.Add(loan);
                        _db.SaveChanges();
                        Session["Message"] = "3";
                    }
                    else
                    {
                        Session["Message"] = "4";
                    }
                }
                else
                {
                    Session["Message"] = "5";
                }
            }
                return RedirectToAction("Index","Books","");
        }
        [HttpPost]
        public ActionResult EndLoan(int id)
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Users");
            }
            var loan = _db.Loan.Where(x => x.Id.Equals(id)).FirstOrDefault();
            loan.EndOfLoan = DateTime.Now;
            var book = _db.Book.Where(x => x.Id.Equals(loan.BookId)).FirstOrDefault();
            book.Quantity += 1;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Biblioteka/Views/Loans/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
@if (ViewBag.Message != null)
{
    <script>

$(document).ready(function(){

alert('@ViewBag.Message');

});

    </script>

}
<div class="row justify-content-md-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                Aktywne wypożyczenia
            </div>
            <div class="card-body">
                <table class="table">
                    <thead class="tab-pane">
                        <tr>
                            <th>Id</th>
                            <th>Książka</th>
                            <th>Data wypożyczenia</th>
                        </tr>
                    </thead>
                    <tbody class="tab-content">
                        @foreach (var item in Model)
                        {
                            if (item.Status == "Active")
                            {
                                <tr>
                                    <td>
                                        @item.Id
                                    </td>
                                    <td>
                                        @item.BookName
                                    </td>
                                    <td>
                                        @item.StartOfLoan
                                    </td>
                                    <td>
                                    <td>
                                        @using (Html.BeginForm("EndLoan", "Loans", FormMethod.Post))
                                        {
                                            <div class="form-group">
                                                <input type="hidden" name="id" value="@item.Id" />
                                                <input type="submit" name="submit" class="btn btn-primary" value="Zakończ wypożyczenie" />
                                            </div>
                                        }

                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-md-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                Zakończone wypożyczenia
            </div>
            <div class="card-body">
                <table class="table">
                    <thead class="tab-pane">
                        <tr>
                            <th>Id</th>
                            <th>Książka</th>
                            <th>Data wypożyczenia</th>
                            <th>Data zwrotu</th>
                        </tr>
                    </thead>
                    <tbody class="tab-content">
                        @foreach (var item in Model)
                        {
                            if (item.Status == "Ended")
                            {
                                <tr>
                                    <td>
                                        @item.Id
                                    </td>
                                    <td>
                                        @item.BookName
                                    </td>
                                    <td>
                                        @item.StartOfLoan
                                    </td>
                                    <td>
                                        @item.EndOfLoan
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>